project:
  type: website

pagetitle: "Laboratory of Microbial Symbiosis, Ecology, and Evolution"
website:
  site-url: "https://chang-yu-chang.github.io/changlab/"
  favicon: "images/index/logo.png"
  google-analytics: "G-Q3LJHCQ46Q"
  navbar:
    logo: 
      light: images/index/asset_white_text.png
      dark: images/index/asset_white_text.png
    logo-alt: "Laboratory of Microbial Symbiosis, Ecology, and Evolution"
    right:
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Join Us
        href: join.qmd
  page-footer:
    left: "© 2025 Laboratory of Microbial Ecology and Evolution"
    right: "Logo and assets design by Yueh Lu 盧悅"

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
      dark:
        - darkly
        - styles.scss
