project:
  type: website

website:
  title: "Laboratory of Microbial Symbiosis, Ecology, and Evolution"
  site-url: "https://chang-yu-chang.github.io/changlab/"
  favicon: "images/index/logo.png"
  google-analytics: "G-Q3LJHCQ46Q"
  navbar:
    right:
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Join Us
        href: join.qmd

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
      dark:
        - darkly
        - styles.scss