project:
  type: website

website:
  title: "Laboratory of Microbial Symbiosis, Ecology, and Evolution"
  site-url: "https://chang-yu-chang.github.io/changlab/"
  favicon: "images/index/logo.png"
  navbar:
    right:
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Join Us
        href: join.qmd
  page-footer:
    left: |
      © {{< meta year >}} Chang Lab · Biodiversity Research Center, Academia Sinica
    right: |
      Built with <a href="https://quarto.org">Quarto</a>

format:
  html:
    theme:
      light: flatly
      dark: slate
    css: styles.scss
    toc: false
    smooth-scroll: true

# small variable to print the current year in footer
metadata-files: [_variables.yml]