project:
  type: website
website:
  title: "My Lab"
  navbar:
    left:
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Join
        href: join.qmd
format:
  html:
    theme: cosmo
